# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  ihelp-app:
    image: ihelp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ihelp-postgresql:5432/ihelp
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://ihelp-postgresql:5432/ihelp
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
    restart: always
    healthcheck:
      # test: ["CMD", "pg_isready -U postgres"]
      test: curl -f localhost:8080/actuator/health
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      ihelp-postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy



  ihelp-postgresql:
    image: postgres:13.4
    # volumes:
    #   - ~/volumes/jhipster/ihelp/postgresql/:/var/lib/postgresql/data/
    environment:
      - PGDATABASE=ihelp
      - POSTGRES_USER=ihelp
      - POSTGRES_PASSWORD=ihelp
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    healthcheck:
      # test: ["CMD", "pg_isready -U postgres"]
      test: pg_isready -U postgres
      interval: 7s
      timeout: 4s
      retries: 30

  keycloak:
    image: jboss/keycloak:15.0.2
    command:
      [
        '-b',
        '0.0.0.0',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
        '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
        '-Djboss.socket.binding.port-offset=1000',
        '-Dkeycloak.profile.feature.upload_scripts=enabled',
      ]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9080:9080
      - 127.0.0.1:9443:9443
      - 127.0.0.1:10990:10990
    restart: always
    healthcheck:
      # test: ["CMD", "pg_isready -U postgres"]
      test: curl -f http://localhost:9080/auth/
      interval: 7s
      timeout: 4s
      retries: 10
    depends_on:
      ihelp-postgresql:
        condition: service_healthy
